import Head from "next/head";

const HeadPage = () => {
  return (
    <Head>
      <title>Gaskeuun App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadPage;
